#!/usr/bin/env python3
"""
Operability Analysis of a Natural Gas Processing Plant
=======================================================

This script performs a comprehensive process-operability analysis on a
Latin Hypercube Sampling (LHS) dataset generated by DWSIM simulations
of a natural gas processing plant.

The analysis follows the operability framework of Vinson & Georgakis
(2000), extended by Gazzaneo et al. (2020) and implemented with
concepts from the Opyrability package (Alves et al., 2024).

Framework:
    AIS  – Available Input Set   (5 decision variables, manipulated)
    AOS  – Achievable Output Set (mapped outputs from simulation)
    DOS  – Desired Output Set    (defined by product-quality constraints)
    OI   – Operability Index = |AOS ∩ DOS| / |AOS| × 100 %

Decision variables (AIS) – using real stage temperatures:
    u1 = V_02_Temp    (°C)  – cold separator temperature  (V-02)
    u2 = T_01_Reb     (°C)  – deethaniser reboiler temp.  (T-01, stage 11)
    u3 = T_02_RR      (–)   – debutanizer reflux ratio    (T-02)
    u4 = T_02_Reb     (°C)  – debutanizer reboiler temp.  (T-02, stage 21)
    u5 = T_03_Reb     (°C)  – stabilizer reboiler temp.   (T-03, stage 6)

Outputs / Constraints (DOS):
    y1 = Revenue       ($/h)  – objective (maximise)
    g1 = SG_C1    ≥ 80        – methane in Sales Gas (mol%)
    g2 = LPG_C2   ≤ 12        – ethane in LPG (mol%)
    g3 = LPG_C5   ≤  2        – C5+ in LPG (mol%)
    g4 = NG_RVP   ≤ 76        – Reid Vapour Pressure of Natural Gasoline (kPa)

Authors : Gabriel Freitas, Roymel R. Carpio, Nicolas Spogis
          UFRJ / UNICAMP
Date    : 2026
"""

# ============================================================
# 0.  Imports and configuration
# ============================================================
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")  # non-interactive backend
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from matplotlib.patches import FancyBboxPatch, Rectangle
from matplotlib.lines import Line2D
import seaborn as sns
from itertools import combinations
import scipy.stats as stats
import warnings
warnings.filterwarnings("ignore")

# ── Output directories ────────────────────────────────────────
import os
FIGDIR = "figures"
TABDIR = "tables"
os.makedirs(FIGDIR, exist_ok=True)
os.makedirs(TABDIR, exist_ok=True)

# ── Publication-quality defaults ─────────────────────────────
plt.rcParams.update({
    "font.family":       "serif",
    "font.serif":        ["Times New Roman", "DejaVu Serif"],
    "mathtext.fontset":  "dejavuserif",
    "font.size":         10,
    "axes.titlesize":    11,
    "axes.labelsize":    10,
    "xtick.labelsize":   9,
    "ytick.labelsize":   9,
    "legend.fontsize":   8.5,
    "figure.dpi":        200,
    "savefig.dpi":       300,
    "savefig.bbox":      "tight",
    "axes.grid":         False,
    "axes.spines.top":   False,
    "axes.spines.right": False,
})

# Colour palette (colour-blind safe)
C_FEAS   = "#2ca02c"   # green  – feasible
C_INFEAS = "#d62728"   # red    – infeasible
C_OBJ    = "#1f77b4"   # blue   – objective
C_ACCENT = "#ff7f0e"   # orange – highlights

# ============================================================
# 1.  Load data and rename columns
# ============================================================
print("=" * 70)
print("OPERABILITY ANALYSIS – Natural Gas Processing Plant")
print("=" * 70)

df = pd.read_csv("../datasets/dataset_clean.csv")
N = len(df)
print(f"\nDataset loaded: {N} LHS samples, {df.shape[1]} columns")

# ── Rename to paper nomenclature ─────────────────────────────
# The dataset contains:
#   - 5 original DWSIM decision vars (recovery fractions / reflux ratio)
#   - 5 outputs
#   - 6 real stage temperatures (top + bottom of T-01, T-02, T-03)
#
# We use the REAL BOTTOM TEMPERATURES as the decision variables

df = df.rename(columns={
    # Real stage temperatures → paper decision variables
    "T_123701_Stage11_Temperature": "T_01_Reb",   # Deethaniser bottom (11 stages)
    "T_123702_Stage21_Temperature": "T_02_Reb",   # Debutanizer bottom (21 stages)
    "T_123703_Stage6_Temperature":  "T_03_Reb",   # Stabilizer bottom  (6 stages)
    # Cold separator stays the same (already a temperature)
    "V_123102_Temp": "V_02_Temp",
    # Reflux ratio (NOT a temperature — dimensionless)
    "T_123702_Condenser": "T_02_RR",
    # Top temperatures (kept for reference, not used as DVs)
    "T_123701_Stage1_Temperature": "T_01_Top",
    "T_123702_Stage1_Temperature": "T_02_Top",
    "T_123703_Stage1_Temperature": "T_03_Top",
    # Outputs → paper names
    "GVC1":     "SG_C1",
    "GVC2":     "LPG_C2",
    "GVC5":     "LPG_C5",
    "GVC5_PVR": "NG_RVP",
})

# Revenue: stored as negative cost in Sales_Price → convert to positive
df["Revenue"] = df["Sales_Price"].abs()

# ── Column mapping ───────────────────────────────────────────
# Decision variables for the paper (real temperatures + reflux ratio)
decision_vars = [
    "V_02_Temp",   # u1: cold separator temperature (°C)
    "T_01_Reb",    # u2: deethaniser reboiler temperature (°C)
    "T_02_RR",     # u3: debutanizer reflux ratio (–)
    "T_02_Reb",    # u4: debutanizer reboiler temperature (°C)
    "T_03_Reb",    # u5: stabilizer reboiler temperature (°C)
]
dv_labels = [
    r"$u_1$: $T_{\mathrm{V\text{-}02}}$ (°C)",
    r"$u_2$: $T_{\mathrm{reb,T\text{-}01}}$ (°C)",
    r"$u_3$: RR$_{\mathrm{T\text{-}02}}$ (–)",
    r"$u_4$: $T_{\mathrm{reb,T\text{-}02}}$ (°C)",
    r"$u_5$: $T_{\mathrm{reb,T\text{-}03}}$ (°C)",
]
dv_short = ["V-02 Temp", "T-01 Reb", "T-02 RR", "T-02 Reb", "T-03 Reb"]
dv_units = ["°C", "°C", "–", "°C", "°C"]

obj_col = "Revenue"

constraint_cols = ["SG_C1", "LPG_C2", "LPG_C5", "NG_RVP"]
constraint_specs = {
    "SG_C1":  {"lb": 80.0, "ub": np.inf, "label": r"$g_1$: SG_C$_1$ $\geq$ 80"},
    "LPG_C2": {"lb":  0.0, "ub": 12.0,   "label": r"$g_2$: LPG_C$_2$ $\leq$ 12"},
    "LPG_C5": {"lb":  0.0, "ub":  2.0,   "label": r"$g_3$: LPG_C$_5$ $\leq$ 2"},
    "NG_RVP": {"lb":  0.0, "ub": 76.0,   "label": r"$g_4$: NG_RVP $\leq$ 76"},
}
active_constraints = ["LPG_C2", "LPG_C5", "NG_RVP"]

# ── SLSQP optimal point (real temperatures from simulation) ──
optimal = {
    "V_02_Temp": -33.00,
    "T_01_Reb":   66.29,
    "T_02_RR":     4.31,
    "T_02_Reb":  140.11,
    "T_03_Reb":  197.24,
    "Revenue":   663.85,
    "SG_C1":      83.74,
    "LPG_C2":     12.00,
    "LPG_C5":      0.01,
    "NG_RVP":     76.00,
}


# ============================================================
# 2.  Feasibility assessment
# ============================================================
print("\n" + "─" * 70)
print("SECTION 1 – FEASIBILITY ASSESSMENT")
print("─" * 70)

# Helper function
def count_feasible(df, specs):
    """Count feasible points under given constraint specs."""
    mask = pd.Series(True, index=df.index)
    for col, s in specs.items():
        if np.isfinite(s["lb"]):
            mask &= df[col] >= s["lb"]
        if np.isfinite(s["ub"]):
            mask &= df[col] <= s["ub"]
    return mask.sum(), mask

# Per-constraint masks
masks = {}
for col, spec in constraint_specs.items():
    m = pd.Series(True, index=df.index)
    if np.isfinite(spec["lb"]):
        m &= df[col] >= spec["lb"]
    if np.isfinite(spec["ub"]):
        m &= df[col] <= spec["ub"]
    masks[col] = m

# Individual feasibility
print(f"\n{'Constraint':<12} {'Feasible':>10} {'Violated':>10} {'Feas %':>8}")
print("-" * 44)
for col, m in masks.items():
    nf = m.sum()
    nv = N - nf
    print(f"{col:<12} {nf:>10} {nv:>10} {100*nf/N:>7.1f}%")

# Overall
feas_all = pd.Series(True, index=df.index)
for m in masks.values():
    feas_all &= m
df["feasible"] = feas_all
n_feas = feas_all.sum()
print(f"\n{'ALL':<12} {n_feas:>10} {N-n_feas:>10} {100*n_feas/N:>7.1f}%")

# OI (Operability Index) approximated from LHS coverage
OI = 100.0 * n_feas / N
print(f"\n>>> Operability Index (OI) ≈ {OI:.1f} %")
print(f"    ({n_feas} of {N} AIS samples map into the DOS)")

# Pairwise feasibility
print(f"\n{'Constraint Pair':<25} {'Joint Feas %':>12}")
print("-" * 39)
for c1, c2 in combinations(active_constraints, 2):
    joint = masks[c1] & masks[c2]
    print(f"{c1 + ' ∩ ' + c2:<25} {100*joint.sum()/N:>11.1f}%")

# ============================================================
# 3.  AIS and AOS characterisation
# ============================================================
print("\n" + "─" * 70)
print("SECTION 2 – AIS / AOS CHARACTERISATION")
print("─" * 70)

print(f"\n{'Variable':<14} {'Min':>10} {'Max':>10} {'Range':>10} {'Unit':>6}")
print("-" * 55)
print("--- Available Input Set (AIS) ---")
for v, u in zip(decision_vars, dv_units):
    lo, hi = df[v].min(), df[v].max()
    print(f"{v:<14} {lo:>10.2f} {hi:>10.2f} {hi-lo:>10.2f} {u:>6}")
print("\n--- Achievable Output Set (AOS) ---")
for v in [obj_col] + constraint_cols:
    lo, hi = df[v].min(), df[v].max()
    print(f"{v:<14} {lo:>10.4f} {hi:>10.4f} {hi-lo:>10.4f}")

# Feasible vs infeasible DV comparison
print(f"\n{'Variable':<14} {'μ_feas':>9} {'μ_infeas':>10} {'Shift':>9}")
print("-" * 46)
for v in decision_vars:
    mf = df.loc[feas_all, v].mean()
    mi = df.loc[~feas_all, v].mean()
    print(f"{v:<14} {mf:>9.2f} {mi:>10.2f} {mf-mi:>+9.2f}")

# ============================================================
# 4.  Correlation analysis (using real temperatures)
# ============================================================
print("\n" + "─" * 70)
print("SECTION 3 – CORRELATION ANALYSIS (real temperatures)")
print("─" * 70)

print(f"\n--- Decision Vars × Revenue ---")
for v in decision_vars:
    r = df[v].corr(df[obj_col])
    stars = "***" if abs(r) > 0.5 else "**" if abs(r) > 0.3 else "*" if abs(r) > 0.1 else ""
    print(f"  {v:<14} r = {r:>+.4f}  {stars}")

print(f"\n--- Decision Vars × Active Constraints ---")
header = f"{'DV':<14}" + "".join(f"{c:>12}" for c in active_constraints)
print(header)
print("-" * len(header))
for v in decision_vars:
    row = f"{v:<14}"
    for c in active_constraints:
        r = df[v].corr(df[c])
        flag = " *" if abs(r) > 0.3 else ""
        row += f"{r:>+10.4f}{flag:>2}"
    print(row)

print(f"\n--- Output–Output Correlations ---")
for c1, c2 in combinations(constraint_cols, 2):
    r = df[c1].corr(df[c2])
    if abs(r) > 0.2:
        print(f"  {c1} × {c2}: r = {r:>+.4f}")

# Key correlations for the paper
print(f"\n--- Key Correlations (Table 5) ---")
key_pairs = [
    ("V_02_Temp", "Revenue",  "Colder separator → more liquid → higher revenue"),
    ("T_01_Reb",  "LPG_C2",  "Hotter T-01 reboiler → less ethane in LPG"),
    ("T_02_Reb",  "NG_RVP",  "Hotter T-02 reboiler → lower RVP of NG"),
    ("LPG_C5",   "NG_RVP",   "More C5+ in LPG → less light ends in NG → lower RVP"),
]
for x, y, mechanism in key_pairs:
    r, p = stats.pearsonr(df[x], df[y])
    print(f"  r({x}, {y}) = {r:+.4f}  (p={p:.2e})  — {mechanism}")

# ============================================================
# 5.  Constraint sensitivity / relaxation analysis
# ============================================================
print("\n" + "─" * 70)
print("SECTION 4 – CONSTRAINT SENSITIVITY ANALYSIS")
print("─" * 70)

# 5a.  Relaxation: remove one constraint at a time
print("\n--- (a) Single-constraint relaxation ---")
print(f"  Baseline OI = {OI:.1f}%\n")
relax_data = {}
for remove_col in constraint_cols:
    specs_relaxed = {k: v for k, v in constraint_specs.items() if k != remove_col}
    n_rel, _ = count_feasible(df, specs_relaxed)
    oi_rel = 100 * n_rel / N
    gain = oi_rel - OI
    relax_data[remove_col] = oi_rel
    print(f"  Remove {remove_col:<10}:  OI = {oi_rel:>5.1f}%   (Δ = +{gain:.1f} pp)")

# 5b.  Tightening sweeps
print("\n--- (b) Constraint-tightening sweeps ---")
sweep_configs = {
    "LPG_C2": np.arange(4, 17, 0.5),
    "LPG_C5": np.arange(0.2, 5.2, 0.2),
    "NG_RVP": np.arange(40, 102, 2),
}
sweep_results = {}
for col, ub_range in sweep_configs.items():
    ois = []
    for ub in ub_range:
        specs_mod = dict(constraint_specs)
        specs_mod[col] = {"lb": constraint_specs[col]["lb"], "ub": ub,
                          "label": constraint_specs[col]["label"]}
        n, _ = count_feasible(df, specs_mod)
        ois.append(100 * n / N)
    sweep_results[col] = (ub_range, np.array(ois))
    print(f"  {col}: swept ub ∈ [{ub_range[0]:.1f}, {ub_range[-1]:.1f}]")

# 5c.  Violation magnitude analysis
print("\n--- (c) Violation magnitude statistics ---")
print(f"  {'Constraint':<12} {'Viol. count':>12} {'Mean viol.':>12} {'Max viol.':>12} {'95th pct.':>12}")
print("  " + "-" * 62)
for col in active_constraints:
    spec = constraint_specs[col]
    violated = ~masks[col]
    if violated.sum() == 0:
        print(f"  {col:<12} {'0':>12} {'—':>12} {'—':>12} {'—':>12}")
        continue
    if np.isfinite(spec["ub"]):
        viol_vals = df.loc[violated, col] - spec["ub"]
    else:
        viol_vals = spec["lb"] - df.loc[violated, col]
    viol_vals = viol_vals.abs()
    print(f"  {col:<12} {violated.sum():>12} {viol_vals.mean():>12.3f} "
          f"{viol_vals.max():>12.3f} {viol_vals.quantile(0.95):>12.3f}")

# ============================================================
# 6.  Optimal feasible point (from LHS)
# ============================================================
print("\n" + "─" * 70)
print("SECTION 5 – OPTIMAL FEASIBLE POINT")
print("─" * 70)

df_feas = df[feas_all]
best_idx = df_feas[obj_col].idxmax()   # Revenue is positive now → idxmax
best = df_feas.loc[best_idx]

print(f"\n  Best feasible index: {best_idx}")
print(f"  Revenue = {best[obj_col]:.4f} $/h\n")
print(f"  Decision variables:")
for v, u in zip(decision_vars, dv_units):
    print(f"    {v:<14} = {best[v]:>10.4f}  {u}")
print(f"\n  Constraint values:")
for col, spec in constraint_specs.items():
    val = best[col]
    lb = spec["lb"]
    ub = spec["ub"]
    status = "✓"
    if np.isfinite(lb) and val < lb:
        status = "✗"
    if np.isfinite(ub) and val > ub:
        status = "✗"
    if np.isfinite(ub):
        margin = ub - val
        margin_str = f"margin = {margin:.4f}"
    else:
        margin = val - lb
        margin_str = f"margin = {margin:.4f}"
    print(f"    {col:<12} = {val:>10.4f}   {status}   ({margin_str})")

print(f"\n  Feasible region statistics:")
print(f"    Revenue: best = {df_feas[obj_col].max():.2f},  "
      f"worst = {df_feas[obj_col].min():.2f},  "
      f"mean = {df_feas[obj_col].mean():.2f},  "
      f"σ = {df_feas[obj_col].std():.2f} $/h")

# SLSQP comparison
print(f"\n  SLSQP optimal: Revenue = {optimal['Revenue']:.2f} $/h")
print(f"  Improvement over best LHS: "
      f"{100*(optimal['Revenue'] - best[obj_col])/best[obj_col]:.1f}%")

# ============================================================
# 7.  FIGURES
# ============================================================
print("\n" + "─" * 70)
print("GENERATING FIGURES …")
print("─" * 70)


# ──────────────────────────────────────────────────────────────
# FIG 1 – Parallel Coordinates (AIS coloured by feasibility)
# ──────────────────────────────────────────────────────────────
fig, ax = plt.subplots(figsize=(8, 4))

df_norm = df[decision_vars].copy()
for v in decision_vars:
    vmin, vmax = df[v].min(), df[v].max()
    df_norm[v] = (df[v] - vmin) / (vmax - vmin)

# Infeasible background
for _, row in df_norm[~feas_all].iterrows():
    ax.plot(range(len(decision_vars)), [row[v] for v in decision_vars],
            color=C_INFEAS, alpha=0.04, linewidth=0.4)
# Feasible foreground
for _, row in df_norm[feas_all].iterrows():
    ax.plot(range(len(decision_vars)), [row[v] for v in decision_vars],
            color=C_FEAS, alpha=0.35, linewidth=0.6)

# SLSQP optimal
opt_norm = []
for v in decision_vars:
    vmin, vmax = df[v].min(), df[v].max()
    opt_norm.append((optimal[v] - vmin) / (vmax - vmin) if vmax > vmin else 0.5)
ax.plot(range(len(decision_vars)), opt_norm, color=C_ACCENT, lw=2.5,
        marker="o", markersize=7, zorder=10, label=f"SLSQP optimal ({optimal['Revenue']:.0f} $/h)")

ax.set_xticks(range(len(decision_vars)))
ax.set_xticklabels(dv_short, fontsize=9)
ax.set_ylabel("Normalised value  [0, 1]")
ax.set_title("Parallel coordinates — AIS coloured by feasibility")

# Real-value annotations
for i, v in enumerate(decision_vars):
    ax.text(i, -0.08, f"{df[v].min():.1f}", ha="center", fontsize=7, color="0.45")
    ax.text(i, 1.06, f"{df[v].max():.1f}", ha="center", fontsize=7, color="0.45")

legend_els = [
    Line2D([0], [0], color=C_FEAS, lw=1.8, label=f"Feasible  (n = {n_feas})"),
    Line2D([0], [0], color=C_INFEAS, lw=1.8, alpha=0.45,
           label=f"Infeasible  (n = {N - n_feas})"),
    Line2D([0], [0], color=C_ACCENT, lw=2.5, marker="o", markersize=6,
           label=f"SLSQP optimal ({optimal['Revenue']:.0f} $/h)"),
]
ax.legend(handles=legend_els, loc="upper right", framealpha=0.9)
plt.tight_layout()
plt.savefig(f"{FIGDIR}/fig1_parallel_coordinates.png")
plt.savefig(f"{FIGDIR}/fig1_parallel_coordinates.pdf")
plt.close()
print("  ✓ Figure 1 – Parallel coordinates")


# ──────────────────────────────────────────────────────────────
# FIG 2 – AOS projections with DOS constraint boundaries
# ──────────────────────────────────────────────────────────────
pairs = [
    ("LPG_C2", "NG_RVP"),
    ("LPG_C2", "LPG_C5"),
    ("LPG_C5", "NG_RVP"),
]
dos_limits = {
    "LPG_C2": {"val": 12, "color": "navy",    "label": r"LPG_C$_2$ = 12"},
    "LPG_C5": {"val":  2, "color": "navy",    "label": r"LPG_C$_5$ = 2"},
    "NG_RVP": {"val": 76, "color": "darkred", "label": r"NG_RVP = 76"},
}

fig, axes = plt.subplots(1, 3, figsize=(14, 4.2))
for idx, (xv, yv) in enumerate(pairs):
    ax = axes[idx]
    # Infeasible
    ax.scatter(df.loc[~feas_all, xv], df.loc[~feas_all, yv],
               c=C_INFEAS, alpha=0.08, s=8, rasterized=True)
    # Feasible
    ax.scatter(df.loc[feas_all, xv], df.loc[feas_all, yv],
               c=C_FEAS, alpha=0.55, s=14, edgecolors="darkgreen",
               linewidths=0.25, rasterized=True)
    # SLSQP optimal
    ax.scatter(optimal[xv], optimal[yv], c=C_ACCENT, s=100, marker="*",
               edgecolors="black", linewidths=0.8, zorder=10)
    # Constraint lines
    if xv in dos_limits:
        dl = dos_limits[xv]
        ax.axvline(dl["val"], color=dl["color"], ls="--", lw=1.2,
                   label=dl["label"], zorder=5)
    if yv in dos_limits:
        dl = dos_limits[yv]
        ax.axhline(dl["val"], color=dl["color"], ls="--", lw=1.2,
                   label=dl["label"], zorder=5)
    # DOS region shading
    if xv in dos_limits and yv in dos_limits:
        x_lim = dos_limits[xv]["val"]
        y_lim = dos_limits[yv]["val"]
        dos_rect = Rectangle((0, 0), x_lim, y_lim, linewidth=0,
                              edgecolor="none", facecolor=C_FEAS,
                              alpha=0.08, zorder=0)
        ax.add_patch(dos_rect)
    ax.set_xlabel(xv.replace("_", r"_"))
    ax.set_ylabel(yv.replace("_", r"_"))
    ax.legend(fontsize=7.5, loc="best", framealpha=0.9)
    ax.set_title(f"({chr(97+idx)})  {xv} vs {yv}")

plt.suptitle("AOS projections with DOS constraint boundaries",
             fontsize=11, fontweight="bold", y=1.02)
plt.tight_layout()
plt.savefig(f"{FIGDIR}/fig2_aos_projections.png")
plt.savefig(f"{FIGDIR}/fig2_aos_projections.pdf")
plt.close()
print("  ✓ Figure 2 – AOS projections")


# ──────────────────────────────────────────────────────────────
# FIG 3 – Constraint sensitivity (bar chart + relaxation)
# ──────────────────────────────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(11, 4.2))

# (a) Per-constraint feasibility
ax = axes[0]
cols  = list(masks.keys())
pcts  = [100 * masks[c].sum() / N for c in cols]
bars_colors = [C_FEAS if p == 100 else C_ACCENT if p > 60 else C_INFEAS for p in pcts]
bars = ax.bar(cols, pcts, color=bars_colors, edgecolor="black", linewidth=0.5, alpha=0.85)
for bar, p in zip(bars, pcts):
    ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 1,
            f"{p:.1f}%", ha="center", fontsize=8.5, fontweight="bold")
ax.axhline(OI, color="black", ls="--", lw=1, label=f"All constraints: {OI:.1f}%")
ax.set_ylabel("Feasible samples (%)")
ax.set_ylim(0, 110)
ax.legend(fontsize=8)
ax.set_title("(a)  Individual constraint feasibility")

# (b) Relaxation analysis
ax = axes[1]
relax_labels = list(relax_data.keys())
relax_vals = [relax_data[k] for k in relax_labels]
colors = ["#4CAF50", "#3498db", "#9b59b6", "#e74c3c"]
bars = ax.barh(relax_labels, relax_vals, color=colors, edgecolor="black",
               linewidth=0.5, alpha=0.85)
for bar, v in zip(bars, relax_vals):
    ax.text(bar.get_width() + 0.5, bar.get_y() + bar.get_height() / 2,
            f"{v:.1f}% (+{v - OI:.1f})", va="center", fontsize=8.5, fontweight="bold")
ax.axvline(OI, color="black", ls="--", lw=1, label=f"Baseline: {OI:.1f}%")
ax.set_xlabel("OI (%)")
ax.set_xlim(0, 45)
ax.legend(fontsize=8, loc="lower right")
ax.set_title("(b)  OI gain from single-constraint relaxation")

plt.tight_layout()
plt.savefig(f"{FIGDIR}/fig3_constraint_sensitivity.png")
plt.savefig(f"{FIGDIR}/fig3_constraint_sensitivity.pdf")
plt.close()
print("  ✓ Figure 3 – Constraint sensitivity")


# ──────────────────────────────────────────────────────────────
# FIG 4 – OI sensitivity to constraint tightening (3 subplots)
# ──────────────────────────────────────────────────────────────
fig, axes = plt.subplots(1, 3, figsize=(14, 4))
for idx, (col, (ubs, ois_arr)) in enumerate(sweep_results.items()):
    ax = axes[idx]
    ax.plot(ubs, ois_arr, "o-", color="#2c3e50", markersize=2.5, linewidth=1.3)
    current_ub = constraint_specs[col]["ub"]
    ax.axvline(current_ub, color=C_INFEAS, ls="--", lw=1.3,
               label=f"Current = {current_ub:.0f}")
    ax.axhline(OI, color="0.6", ls=":", lw=0.8)
    ax.set_xlabel(f"{col} upper bound")
    ax.set_ylabel("OI (%)")
    ax.set_title(f"({chr(97+idx)})  OI vs {col} limit")
    ax.legend(fontsize=8)
    ax.grid(True, alpha=0.2)

plt.suptitle("Operability Index sensitivity to constraint bounds",
             fontsize=11, fontweight="bold", y=1.02)
plt.tight_layout()
plt.savefig(f"{FIGDIR}/fig4_oi_tightening.png")
plt.savefig(f"{FIGDIR}/fig4_oi_tightening.pdf")
plt.close()
print("  ✓ Figure 4 – OI tightening sweeps")


# ──────────────────────────────────────────────────────────────
# FIG 5 – Decision-variable distributions (feasible vs infeas.)
# ──────────────────────────────────────────────────────────────
fig, axes = plt.subplots(1, 5, figsize=(16, 3.5))
for i, (v, lab) in enumerate(zip(decision_vars, dv_short)):
    ax = axes[i]
    ax.hist(df.loc[~feas_all, v], bins=30, alpha=0.35, color=C_INFEAS,
            density=True, label="Infeasible")
    ax.hist(df.loc[feas_all, v], bins=20, alpha=0.65, color=C_FEAS,
            density=True, label="Feasible")
    ax.axvline(df.loc[feas_all, v].mean(), color="darkgreen", ls="--", lw=1.3)
    ax.axvline(df.loc[~feas_all, v].mean(), color="darkred", ls="--", lw=1.3)
    ax.set_xlabel(lab)
    if i == 0:
        ax.set_ylabel("Density")
    if i == 0:
        ax.legend(fontsize=7)
    ax.set_title(f"({chr(97+i)})")

plt.suptitle("Decision-variable distributions by feasibility",
             fontsize=11, fontweight="bold", y=1.04)
plt.tight_layout()
plt.savefig(f"{FIGDIR}/fig5_dv_distributions.png")
plt.savefig(f"{FIGDIR}/fig5_dv_distributions.pdf")
plt.close()
print("  ✓ Figure 5 – DV distributions")


# ──────────────────────────────────────────────────────────────
# FIG 6 – Feasible region in AIS 2-D projections (colour=revenue)
# ──────────────────────────────────────────────────────────────
proj_pairs = [
    ("V_02_Temp", "T_01_Reb"),
    ("V_02_Temp", "T_02_Reb"),
    ("T_01_Reb",  "T_02_Reb"),
    ("T_02_RR",   "T_03_Reb"),
]

fig, axes = plt.subplots(2, 2, figsize=(10, 8))
for idx, (xv, yv) in enumerate(proj_pairs):
    ax = axes[idx // 2][idx % 2]
    # Infeasible background
    ax.scatter(df.loc[~feas_all, xv], df.loc[~feas_all, yv],
               c="0.85", alpha=0.15, s=6, rasterized=True)
    # Feasible coloured by revenue
    sc = ax.scatter(df.loc[feas_all, xv], df.loc[feas_all, yv],
                    c=df.loc[feas_all, obj_col], cmap="viridis",
                    alpha=0.7, s=18, edgecolors="black",
                    linewidths=0.25, rasterized=True)
    # Best LHS point
    ax.scatter(best[xv], best[yv], c="none", edgecolors=C_ACCENT,
               s=120, linewidths=2.0, marker="*", zorder=10, label="Best LHS")
    # SLSQP optimal
    ax.scatter(optimal[xv], optimal[yv], c=C_ACCENT, s=120, marker="*",
               edgecolors="black", linewidths=0.8, zorder=11, label="SLSQP")
    ax.set_xlabel(dv_short[decision_vars.index(xv)])
    ax.set_ylabel(dv_short[decision_vars.index(yv)])
    ax.set_title(f"({chr(97+idx)})")
    plt.colorbar(sc, ax=ax, label="Revenue ($/h)", shrink=0.85)

plt.suptitle("Feasible region in AIS projections  (colour = revenue)",
             fontsize=11, fontweight="bold", y=1.01)
plt.tight_layout()
plt.savefig(f"{FIGDIR}/fig6_feasible_ais.png")
plt.savefig(f"{FIGDIR}/fig6_feasible_ais.pdf")
plt.close()
print("  ✓ Figure 6 – AIS feasible region")


# ──────────────────────────────────────────────────────────────
# FIG 7 – Correlation heatmap (DVs × outputs)
# ──────────────────────────────────────────────────────────────
all_vars = decision_vars + [obj_col] + constraint_cols
corr = df[all_vars].corr()

fig, ax = plt.subplots(figsize=(8, 6.5))
mask_tri = np.triu(np.ones_like(corr, dtype=bool), k=1)
sns.heatmap(corr, mask=mask_tri, annot=True, fmt=".2f", cmap="RdBu_r",
            center=0, ax=ax, linewidths=0.4, square=True,
            cbar_kws={"shrink": 0.8, "label": "Pearson r"})
ax.set_title("Correlation matrix: decision variables × outputs")
plt.tight_layout()
plt.savefig(f"{FIGDIR}/fig7_correlation_heatmap.png")
plt.savefig(f"{FIGDIR}/fig7_correlation_heatmap.pdf")
plt.close()
print("  ✓ Figure 7 – Correlation heatmap")


# ──────────────────────────────────────────────────────────────
# FIG 8 – Key mechanistic insight: LPG_C5 vs NG_RVP trade-off
#          (full view with all points)
# ──────────────────────────────────────────────────────────────
fig, ax = plt.subplots(figsize=(6, 4.5))
sc = ax.scatter(df["LPG_C5"], df["NG_RVP"], c=df[obj_col], cmap="viridis",
                alpha=0.5, s=12, edgecolors="none", rasterized=True)
ax.axvline(2, color="navy", ls="--", lw=1.2, label=r"LPG_C$_5$ = 2")
ax.axhline(76, color="darkred", ls="--", lw=1.2, label=r"NG_RVP = 76")
# Shade DOS region
dos_rect = Rectangle((0, 0), 2, 76, linewidth=0, edgecolor="none",
                      facecolor=C_FEAS, alpha=0.10, label="DOS region",
                      zorder=0)
ax.add_patch(dos_rect)
# Highlight feasible
ax.scatter(df.loc[feas_all, "LPG_C5"], df.loc[feas_all, "NG_RVP"],
           c=C_FEAS, alpha=0.4, s=18, edgecolors="darkgreen",
           linewidths=0.3, label=f"Feasible (n={n_feas})", zorder=5)
# SLSQP optimal
ax.scatter(optimal["LPG_C5"], optimal["NG_RVP"], c=C_ACCENT, s=120,
           marker="*", edgecolors="black", linewidths=0.8, zorder=10,
           label=f"SLSQP ({optimal['Revenue']:.0f} $/h)")
ax.set_xlabel(r"LPG_C$_5$  (C$_{5+}$ content in LPG, mol%)")
ax.set_ylabel(r"NG_RVP  (Reid Vapour Pressure of NG, kPa)")
ax.set_title(r"LPG_C$_5$ × NG_RVP trade-off with DOS boundary")
plt.colorbar(sc, ax=ax, label="Revenue ($/h)", shrink=0.85)
ax.legend(fontsize=7.5, loc="upper right", framealpha=0.9)
plt.tight_layout()
plt.savefig(f"{FIGDIR}/fig8_lpgc5_ngrvp_tradeoff.png")
plt.savefig(f"{FIGDIR}/fig8_lpgc5_ngrvp_tradeoff.pdf")
plt.close()
print("  ✓ Figure 8 – LPG_C5 × NG_RVP trade-off (full)")


# ──────────────────────────────────────────────────────────────
# FIG 8b – ZOOM: feasible region only, revenue colour scale
# ──────────────────────────────────────────────────────────────
fig, ax = plt.subplots(figsize=(6, 4.5))
sc = ax.scatter(df.loc[feas_all, "LPG_C5"], df.loc[feas_all, "NG_RVP"],
                c=df.loc[feas_all, obj_col], cmap="viridis",
                alpha=0.8, s=30, edgecolors="gray", linewidths=0.3,
                rasterized=True)
# SLSQP optimal
ax.scatter(optimal["LPG_C5"], optimal["NG_RVP"], c=C_ACCENT, s=200,
           marker="*", edgecolors="black", linewidths=0.8, zorder=10,
           label=f"SLSQP ({optimal['Revenue']:.0f} $/h)")
# Best LHS
ax.scatter(best["LPG_C5"], best["NG_RVP"], c="white", s=120,
           marker="*", edgecolors="black", linewidths=0.8, zorder=9,
           label=f"Best LHS ({best[obj_col]:.0f} $/h)")
# Constraint boundaries
ax.axvline(2, color="navy", ls="--", lw=1.5, alpha=0.7, label=r"LPG_C$_5$ = 2")
ax.axhline(76, color="darkred", ls="--", lw=1.5, alpha=0.7, label=r"NG_RVP = 76")

plt.colorbar(sc, ax=ax, label="Revenue ($/h)", shrink=0.85)
# Zoom to feasible region with margin
margin_x = 0.3
margin_y = 8
ax.set_xlim(-margin_x, df.loc[feas_all, "LPG_C5"].max() + margin_x)
ax.set_ylim(df.loc[feas_all, "NG_RVP"].min() - margin_y, 76 + margin_y)
ax.set_xlabel(r"LPG_C$_5$  (C$_{5+}$ content in LPG, mol%)")
ax.set_ylabel(r"NG_RVP  (Reid Vapour Pressure of NG, kPa)")
ax.set_title("Feasible region – Revenue distribution (zoom)")
ax.legend(fontsize=7.5, loc="lower right", framealpha=0.9)
plt.tight_layout()
plt.savefig(f"{FIGDIR}/fig8b_feasible_zoom.png")
plt.savefig(f"{FIGDIR}/fig8b_feasible_zoom.pdf")
plt.close()
print("  ✓ Figure 8b – Feasible region zoom: LPG_C5 × NG_RVP")


# ──────────────────────────────────────────────────────────────
# FIG 8c – ZOOM: LPG_C2 × NG_RVP feasible region (active constraints)
#           (Roymel request: both active constraints at SLSQP optimal)
# ──────────────────────────────────────────────────────────────
fig, ax = plt.subplots(figsize=(6, 4.5))
sc = ax.scatter(df.loc[feas_all, "LPG_C2"], df.loc[feas_all, "NG_RVP"],
                c=df.loc[feas_all, obj_col], cmap="viridis",
                alpha=0.8, s=30, edgecolors="gray", linewidths=0.3,
                rasterized=True)
# SLSQP optimal
ax.scatter(optimal["LPG_C2"], optimal["NG_RVP"], c=C_ACCENT, s=200,
           marker="*", edgecolors="black", linewidths=0.8, zorder=10,
           label=f"SLSQP ({optimal['Revenue']:.0f} $/h)")
# Best LHS
ax.scatter(best["LPG_C2"], best["NG_RVP"], c="white", s=120,
           marker="*", edgecolors="black", linewidths=0.8, zorder=9,
           label=f"Best LHS ({best[obj_col]:.0f} $/h)")
# Constraint boundaries (both active at optimal)
ax.axvline(12, color="navy", ls="--", lw=1.5, alpha=0.7, label=r"LPG_C$_2$ = 12")
ax.axhline(76, color="darkred", ls="--", lw=1.5, alpha=0.7, label=r"NG_RVP = 76")

plt.colorbar(sc, ax=ax, label="Revenue ($/h)", shrink=0.85)
# Zoom to feasible region with margin
margin_x = 1.0
margin_y = 8
ax.set_xlim(df.loc[feas_all, "LPG_C2"].min() - margin_x,
            12 + margin_x)
ax.set_ylim(df.loc[feas_all, "NG_RVP"].min() - margin_y,
            76 + margin_y)
ax.set_xlabel(r"LPG_C$_2$  (Ethane in LPG, mol%)")
ax.set_ylabel(r"NG_RVP  (Reid Vapour Pressure of NG, kPa)")
ax.set_title("Feasible region – Active constraints at optimal (zoom)")
ax.legend(fontsize=7.5, loc="lower left", framealpha=0.9)
plt.tight_layout()
plt.savefig(f"{FIGDIR}/fig8c_feasible_zoom_active.png")
plt.savefig(f"{FIGDIR}/fig8c_feasible_zoom_active.pdf")
plt.close()
print("  ✓ Figure 8c – Feasible region zoom: LPG_C2 × NG_RVP (active constraints)")


# ──────────────────────────────────────────────────────────────
# FIG 9 – Key correlation scatter plots (2×2)
# ──────────────────────────────────────────────────────────────
fig, axes = plt.subplots(2, 2, figsize=(10, 8))

scatter_pairs = [
    ("V_02_Temp", "Revenue",
     r"$u_1$: V-02 Temp. (°C)", "Revenue ($/h)"),
    ("T_01_Reb",  "LPG_C2",
     r"$u_2$: T-01 Reb. Temp. (°C)", r"LPG_C$_2$ – Ethane in LPG (mol%)"),
    ("T_02_Reb",  "NG_RVP",
     r"$u_4$: T-02 Reb. Temp. (°C)", r"NG_RVP – RVP of NG (kPa)"),
    ("LPG_C5",   "NG_RVP",
     r"LPG_C$_5$ – C$_{5+}$ in LPG (mol%)", r"NG_RVP – RVP of NG (kPa)"),
]

for idx, (xvar, yvar, xlabel, ylabel) in enumerate(scatter_pairs):
    ax = axes[idx // 2][idx % 2]

    ax.scatter(df.loc[~feas_all, xvar], df.loc[~feas_all, yvar],
               c=C_INFEAS, alpha=0.08, s=6, rasterized=True, label="Infeasible")
    ax.scatter(df.loc[feas_all, xvar], df.loc[feas_all, yvar],
               c=C_FEAS, alpha=0.5, s=12, edgecolors="darkgreen",
               linewidths=0.25, rasterized=True, label="Feasible")

    # Regression line
    r_val, p_val = stats.pearsonr(df[xvar], df[yvar])
    z = np.polyfit(df[xvar], df[yvar], 1)

    ax.set_xlabel(xlabel)
    ax.set_ylabel(ylabel)
    ax.set_title(f"({chr(97+idx)})  r = {r_val:+.3f}", fontsize=10, style="italic")

    # Constraint limits where relevant
    if yvar == "LPG_C2":
        ax.axhline(12, color="darkred", ls=":", lw=1, alpha=0.6)
    if yvar == "NG_RVP":
        ax.axhline(76, color="darkred", ls=":", lw=1, alpha=0.6)
    if xvar == "LPG_C5":
        ax.axvline(2, color="navy", ls=":", lw=1, alpha=0.6)

    if idx == 0:
        ax.legend(fontsize=7.5, markerscale=2, framealpha=0.9)

plt.suptitle("Key variable correlations",
             fontsize=11, fontweight="bold", y=1.01)
plt.tight_layout()
plt.savefig(f"{FIGDIR}/fig9_key_correlations.png")
plt.savefig(f"{FIGDIR}/fig9_key_correlations.pdf")
plt.close()
print("  ✓ Figure 9 – Key correlation scatter plots")


# ──────────────────────────────────────────────────────────────
# FIG 10 – Violin plots: constraint outputs (feas vs infeas)
# ──────────────────────────────────────────────────────────────
fig, axes = plt.subplots(1, 3, figsize=(12, 4))
for idx, col in enumerate(active_constraints):
    ax = axes[idx]
    data_feas   = df.loc[feas_all,  col].values
    data_infeas = df.loc[~feas_all, col].values

    parts_f = ax.violinplot([data_feas], positions=[0], showmedians=True,
                            showextrema=False)
    for pc in parts_f["bodies"]:
        pc.set_facecolor(C_FEAS)
        pc.set_alpha(0.6)
    parts_f["cmedians"].set_color("darkgreen")

    parts_i = ax.violinplot([data_infeas], positions=[1], showmedians=True,
                            showextrema=False)
    for pc in parts_i["bodies"]:
        pc.set_facecolor(C_INFEAS)
        pc.set_alpha(0.6)
    parts_i["cmedians"].set_color("darkred")

    # Constraint limit line
    spec = constraint_specs[col]
    if np.isfinite(spec["ub"]):
        ax.axhline(spec["ub"], color="navy", ls="--", lw=1.2,
                   label=f"Limit = {spec['ub']:.0f}")
    if np.isfinite(spec["lb"]) and spec["lb"] > 0:
        ax.axhline(spec["lb"], color="navy", ls="--", lw=1.2,
                   label=f"Limit = {spec['lb']:.0f}")

    ax.set_xticks([0, 1])
    ax.set_xticklabels(["Feasible", "Infeasible"])
    ax.set_ylabel(col)
    ax.set_title(f"({chr(97+idx)})  {col}")
    ax.legend(fontsize=7.5)

plt.suptitle("Constraint-output distributions by feasibility",
             fontsize=11, fontweight="bold", y=1.03)
plt.tight_layout()
plt.savefig(f"{FIGDIR}/fig10_violin_constraints.png")
plt.savefig(f"{FIGDIR}/fig10_violin_constraints.pdf")
plt.close()
print("  ✓ Figure 10 – Violin plots")


# ──────────────────────────────────────────────────────────────
# FIG 11 – Revenue vs V-02 Temp (dominant input)
# ──────────────────────────────────────────────────────────────
fig, ax = plt.subplots(figsize=(6, 4.5))
ax.scatter(df.loc[~feas_all, "V_02_Temp"],
           df.loc[~feas_all, obj_col],
           c=C_INFEAS, alpha=0.08, s=8, label="Infeasible", rasterized=True)
ax.scatter(df.loc[feas_all, "V_02_Temp"],
           df.loc[feas_all, obj_col],
           c=C_FEAS, alpha=0.5, s=14, edgecolors="darkgreen",
           linewidths=0.25, label=f"Feasible (n={n_feas})", rasterized=True)
ax.scatter(best["V_02_Temp"], best[obj_col],
           c="white", s=100, marker="*", edgecolors="black",
           linewidths=0.8, zorder=10, label=f"Best LHS ({best[obj_col]:.0f} $/h)")
ax.scatter(optimal["V_02_Temp"], optimal["Revenue"],
           c=C_ACCENT, s=120, marker="*", edgecolors="black",
           linewidths=0.8, zorder=11, label=f"SLSQP ({optimal['Revenue']:.0f} $/h)")
ax.set_xlabel(r"$u_1$: V-02 Temperature (°C)")
ax.set_ylabel("Revenue ($/h)")
ax.set_title("Revenue landscape vs dominant input variable")
ax.legend(fontsize=8)
plt.tight_layout()
plt.savefig(f"{FIGDIR}/fig11_revenue_landscape.png")
plt.savefig(f"{FIGDIR}/fig11_revenue_landscape.pdf")
plt.close()
print("  ✓ Figure 11 – Revenue landscape")


# ============================================================
# 8.  Summary table export
# ============================================================
print("\n" + "─" * 70)
print("EXPORTING SUMMARY TABLES …")
print("─" * 70)

# Table 1: AIS characterisation (with real temperatures)
ais_table = pd.DataFrame({
    "Variable": decision_vars,
    "Label": dv_short,
    "Unit": dv_units,
    "Min": [df[v].min() for v in decision_vars],
    "Max": [df[v].max() for v in decision_vars],
    "Mean_Feasible": [df.loc[feas_all, v].mean() for v in decision_vars],
    "Mean_Infeasible": [df.loc[~feas_all, v].mean() for v in decision_vars],
    "Corr_Revenue": [df[v].corr(df[obj_col]) for v in decision_vars],
})
ais_table.to_csv(f"{TABDIR}/table1_ais_characterisation.csv", index=False, float_format="%.4f")
print("  ✓ table1_ais_characterisation.csv")

# Table 2: Constraint summary
rows = []
for col in constraint_cols:
    spec = constraint_specs[col]
    n_feas_c = masks[col].sum()
    lb = spec["lb"] if np.isfinite(spec["lb"]) else None
    ub = spec["ub"] if np.isfinite(spec["ub"]) else None
    rows.append({
        "Constraint": col,
        "Lower_Bound": lb,
        "Upper_Bound": ub,
        "Feasible_Count": n_feas_c,
        "Feasible_Pct": 100 * n_feas_c / N,
        "AOS_Min": df[col].min(),
        "AOS_Max": df[col].max(),
    })
pd.DataFrame(rows).to_csv(f"{TABDIR}/table2_constraints.csv", index=False, float_format="%.4f")
print("  ✓ table2_constraints.csv")

# Table 3: Relaxation analysis
rows = [{"Removed": "None (baseline)", "OI_pct": OI}]
for rc in constraint_cols:
    specs_r = {k: v for k, v in constraint_specs.items() if k != rc}
    n_r, _ = count_feasible(df, specs_r)
    rows.append({"Removed": rc, "OI_pct": 100 * n_r / N})
pd.DataFrame(rows).to_csv(f"{TABDIR}/table3_relaxation.csv", index=False, float_format="%.2f")
print("  ✓ table3_relaxation.csv")

# Table 4: Best LHS point
opt_data = {v: best[v] for v in decision_vars}
opt_data.update({c: best[c] for c in constraint_cols})
opt_data["Revenue"] = best[obj_col]
pd.DataFrame([opt_data]).to_csv(f"{TABDIR}/table4_best_lhs.csv", index=False, float_format="%.4f")
print("  ✓ table4_best_lhs.csv")

# Table 5: SLSQP optimal point
pd.DataFrame([optimal]).to_csv(f"{TABDIR}/table5_slsqp_optimal.csv", index=False, float_format="%.4f")
print("  ✓ table5_slsqp_optimal.csv")

# Table 6: Full correlation matrix (inputs × outputs)
corr_export = df[all_vars].corr()
corr_export.to_csv(f"{TABDIR}/table6_correlation_matrix.csv", float_format="%.4f")
print("  ✓ table6_correlation_matrix.csv")

# ============================================================
# 9.  Final summary
# ============================================================
print("\n" + "=" * 70)
print("ANALYSIS COMPLETE")
print("=" * 70)
print(f"""
Key findings:
  • Operability Index (OI)      = {OI:.1f}%  ({n_feas}/{N} samples feasible)
  • Non-binding constraint      : SG_C1 ≥ 80  (100% satisfied — always slack)
  • Most restrictive constraint : NG_RVP ≤ 76  (48.5% feasible individually)
  • Tightest pair               : LPG_C5 ∩ NG_RVP  (23.1% joint feasibility)
  • LPG_C5 × NG_RVP correlation : r = {df['LPG_C5'].corr(df['NG_RVP']):+.3f}  (strong inverse coupling)
  • Dominant input variable     : V_02_Temp  (r = {df['V_02_Temp'].corr(df[obj_col]):+.3f} with Revenue)
  • Key correlations (real temperatures):
      T_01_Reb × LPG_C2 : r = {df['T_01_Reb'].corr(df['LPG_C2']):+.3f}  (negative → physical)
      T_02_Reb × NG_RVP  : r = {df['T_02_Reb'].corr(df['NG_RVP']):+.3f}  (negative → physical)
  • Best feasible (LHS)         : {best[obj_col]:.2f} $/h
  • Best feasible (SLSQP)       : {optimal['Revenue']:.2f} $/h  (+{100*(optimal['Revenue']-best[obj_col])/best[obj_col]:.1f}%)

Figures saved:  {FIGDIR}/fig1–fig11  (.png + .pdf)
Tables saved:   {TABDIR}/table1–table6  (.csv)
""")